const WA_NUMBER = "60169322176";
const IMG_BASE = "images/"; // ← change this to your folder name if different

const TABS = [
  { id: "graduation", label: "🎓 Graduation" },
  { id: "valentines", label: "💘 Valentines" },
  { id: "single", label: "🌹 Single Stalk Bouquet" },
  { id: "yellow", label: "💛 Yellow" },
  { id: "purple", label: "💜 Purple" },
  { id: "pink", label: "🩷 Pink" },
  { id: "red", label: "❤️ Red" },
  { id: "cny", label: "🎊 CNY / Moving House / Opening" },
  { id: "mothers", label: "💃 Mother's Day" },
  { id: "teachers", label: "👩‍🏫 Teacher's Day" },
  { id: "basket", label: "🧺 Flower Basket" },
];

const BADGE_CLASS = {
  custom: "badge-custom",
  popular: "badge-popular",
  seasonal: "badge-seasonal",
};
const BADGE_LABEL = {
  custom: "Custom-friendly",
  popular: "Popular",
  seasonal: "Seasonal",
};
const COL_LABEL = {
  graduation: "Graduation",
  valentines: "Valentines",
  single: "Single Stalk Bouquet",
  yellow: "Yellow",
  purple: "Purple",
  pink: "Pink",
  red: "Red",
  cny: "CNY / Moving House / Opening",
  mothers: "Mother's Day",
  teachers: "Teacher's Day",
  basket: "Flower Basket",
};
const BG = {
  graduation: "#e8f5ff",
  valentines: "#ffe8f0",
  single: "#fff0f0",
  yellow: "#fffbe8",
  purple: "#f3e8ff",
  pink: "#ffe8f5",
  red: "#ffe8e8",
  cny: "#fff3e8",
  mothers: "#fce8ff",
  teachers: "#e8fff0",
  basket: "#f0ffe8",
};

// ─── Add products here ───────────────────────────────────────────────────
// collection must match one of the TABS ids above
// badge: 'popular' | 'seasonal' | 'custom' | ''
const PRODUCTS = [
  {
    id: 1,
    name: "🌻 Solo Sun",
    desc: "",
    price: 15,
    img: "single-sunflower.png",
    collection: ["graduation", "single", "teachers"],
    badge: "",
  },
  {
    id: 2,
    name: "🌹 One & Only",
    desc: "",
    price: 21,
    img: "single-rose.png",
    collection: ["single", "valentines", "red"],
    badge: "",
  },
  {
    id: 3,
    name: "🌻🧸 Grad Bear",
    desc: "",
    price: 29,
    img: "small-grad-bear.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 4,
    name: "🌻🎓☁️ Sun & Doll",
    desc: "",
    price: 49,
    img: ["small-sunflower-doll.png", "small-sunflower-doll-1.png"],
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 5,
    name: "🌷☁️ Pink Dream",
    desc: "",
    price: 49,
    img: "3-pink-tulips.png",
    collection: ["pink", "valentines"],
    badge: "",
  },
  {
    id: 6,
    name: "💜☁️ Purple Love",
    desc: "",
    price: 32,
    img: "2-purple-tulips.png",
    collection: ["purple"],
    badge: "",
  },
  {
    id: 7,
    name: "🌻🌸🎓 Pink Bloom",
    desc: "",
    price: 165,
    img: "medium-large-pink-sunflower.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 8,
    name: "🌻☁️ Sun & Mist",
    desc: "",
    price: 39,
    img: "sunflower-fmn.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 9,
    name: "🌻🤍🍊 Sunny Whites",
    desc: "",
    price: 185,
    img: "large-white-sunflower.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 10,
    name: "🌻🌼🤎 Warm Burst",
    desc: "",
    price: 185,
    img: "large-brown-sunflower.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 11,
    name: "🌻🌼 Little Sun",
    desc: "",
    price: 25,
    img: ["small-sunflower.png", "small-sunflower-1.png"],
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 12,
    name: "🎓🩵🫧 Blue Bloom",
    desc: "",
    price: 179,
    img: ["medium-large-blue-lily.png", "medium-large-blue-lily (1).png"],
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 13,
    name: "🌻🌼🤎 Sunny Day",
    desc: "",
    price: 132,
    img: "medium-large-brown-sunflower.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 14,
    name: "🌻🤎🎓 Five Suns",
    desc: "",
    price: 115,
    img: "medium-large-5-sunflowers.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 15,
    name: "🌻🎓💛 Sun & Snoopy",
    desc: "",
    price: 192,
    img: "large-snoopy.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 16,
    name: "🎓🌸 Grad Doll",
    desc: "Available in multiple colours",
    price: 24,
    img: "mini-grad-doll.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 17,
    name: "🌻🤎☁️ Sunny Cheer",
    desc: "",
    price: 135,
    img: "medium-large-single-sunflower.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 18,
    name: "🌸🧚‍♀️🤎 Pastel Dream",
    desc: "",
    price: 155,
    img: "colourful-lily.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 19,
    name: "🌹♠️ Red Velvet",
    desc: "",
    price: 65,
    img: "3-roses.png",
    collection: ["red", "valentines"],
    badge: "",
  },
  {
    id: 20,
    name: "🎓🌻🌸 Joyful Grad",
    desc: "Available in multiple colours ",
    price: 60,
    img: [
      "grad-doll-5-flowers.png",
      "grad-doll-5-flowers (1).png",
      "grad-doll-5-flowers (2).png",
      "grad-doll-5-flowers (3).png",
      "grad-doll-5-flowers (4).png",
    ],
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 21,
    name: "🎓🌸🫧 Pink Crybaby",
    desc: "Includes Crybaby plushie (subject to availability)",
    price: 329,
    img: "large-crybaby.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 22,
    name: "🧸🌻🌼 Teddy Honours",
    desc: "Available in multiple colours",
    price: 65,
    img: [
      "medium-grad-calla-lily.png",
      "medium-grad-calla-lily (5).png",
      "medium-grad-calla-lily (4).png",
      "medium-grad-calla-lily (1).png",
      "medium-grad-calla-lily (2).png",
      "medium-grad-calla-lily (3).png",
    ],
    collection: ["graduation"],
    badge: "",
    height: "40 cm",
    width: "30 cm",
  },
  {
    id: 23,
    name: "🎓🌹 Doll in Rose",
    desc: "",
    price: 65,
    img: "grad-doll-rose.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 24,
    name: "🎓🫧 Premium Grad Doll",
    desc: "Available in multiple colours",
    price: 32,
    img: ["mini-premium-grad-doll.png", "mini-premium-grad-doll (1).png"],
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 25,
    name: "🧸🌸 Teddy & Blooms",
    desc: "Available in multiple colours",
    price: 35,
    img: ["bear-5-flowers.png"],
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 26,
    name: "🌼🤍 Spring Morning",
    desc: "",
    price: 79,
    img: "white-yellow-lily.png",
    collection: ["yellow"],
    badge: "",
  },
  {
    id: 27,
    name: "🌻☁️🩵 Summer Sky",
    desc: "",
    price: 85,
    img: "5-small-sunflowers.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 28,
    name: "🎓🎀☁️ Pink Chapter",
    desc: "",
    price: 128,
    img: "medium-pink-white-ribbon.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 29,
    name: "🧧🧨 Fortune in Red",
    desc: "",
    price: 98,
    img: ["cny (1).png", "cny (3).png", "cny (4).jpeg"],
    collection: ["cny"],
    badge: "",
  },
  {
    id: 30,
    name: "🌻🌸🤎 Wild Bloom",
    desc: "",
    price: 130,
    img: "sunflower-pink-lily.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 31,
    name: "🩵🌿☁️ Powder Blue",
    desc: "",
    price: 125,
    img: "blue-lily-tulips.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 32,
    name: "🌊🤍🫧 Ocean Bloom",
    desc: "",
    price: 249,
    img: "xl-blue-lily.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 33,
    name: "🍷🤍 Wine & White",
    desc: "",
    price: 55,
    img: "red-roses.png",
    collection: ["red", "valentines"],
    badge: "",
  },
  {
    id: 34,
    name: "🌹🌼 Garden Rose",
    desc: "",
    price: 68,
    img: "red-roses-white-flowers.png",
    collection: ["red", "valentines"],
    badge: "",
  },
  {
    id: 35,
    name: "🍭 Cotton Candy",
    desc: "",
    price: 49,
    img: "3-carnation-pink.png",
    collection: ["mothers"],
    badge: "",
  },
  {
    id: 36,
    name: "🎀 Pink for Mum",
    desc: "",
    price: 25,
    img: "single-carnation.png",
    collection: ["mothers"],
    badge: "",
  },
  {
    id: 36,
    name: "🌸✨ Peony Dream",
    desc: "",
    price: 129,
    img: "peony.png",
    collection: ["teachers", "graduation"],
    badge: "",
  },
  {
    id: 38,
    name: "🌸 Pocket Bloom",
    desc: "",
    price: 19,
    img: "single-gradient-rose.png",
    collection: ["mothers", "valentines"],
    badge: "",
  },
  {
    id: 39,
    name: "🌸 Sky Garden",
    desc: "",
    price: 79,
    img: "sunflower-blue-rose.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 40,
    name: "🌷🤎 First Bloom",
    desc: "",
    price: 25,
    img: "small-pink-tulip.png",
    collection: ["valentines", "pink"],
    badge: "",
  },
  {
    id: 41,
    name: "💗☁️ Rose in Lace ",
    desc: "",
    price: 45,
    img: "2-pink-roses.png",
    collection: ["valentines", "pink"],
    badge: "",
  },
  {
    id: 42,
    name: "🎀☁️ Soft Romance ",
    desc: "",
    price: 89,
    img: "white-pink-roses.png",
    collection: ["valentines", "pink"],
    badge: "",
  },
  {
    id: 43,
    name: "🎀🫧 Sweet Pair ",
    desc: "",
    price: 45,
    img: "pink-tulip-fmn.png",
    collection: ["valentines", "pink"],
    badge: "",
  },
  {
    id: 44,
    name: "🌹🩷 Grand Romance ",
    desc: "",
    price: 299,
    img: "xxl-red-roses.png",
    collection: ["valentines", "red"],
    badge: "",
  },
  {
    id: 45,
    name: "🍬 Simple Joy ",
    desc: "",
    price: 15,
    img: "single-tulip.png",
    collection: ["single", "pink", "mothers", "teachers"],
    badge: "",
  },
  {
    id: 46,
    name: "💜🌼 Purple Dream ",
    desc: "",
    price: 120,
    img: "purple-yellow-grad.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 47,
    name: "🌻🌼🤍 Sunny White ",
    desc: "",
    price: 132,
    img: "medium-yellow-white.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 48,
    name: "🎓☀️🍊 Sunset Bloom ",
    desc: "",
    price: 159,
    img: "orange-yellow-grad.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 49,
    name: "🌷🫧 First Blush",
    desc: "",
    price: 79,
    img: "peach-tulips.png",
    collection: ["pink", "valentines"],
    badge: "",
  },
  {
    id: 50,
    name: "🌻🩵☁️ Blue Breeze",
    desc: "",
    price: 105,
    img: "sunflower-blue-white.png",
    collection: ["graduation"],
    badge: "",
  },
  {
    id: 51,
    name: "🤎🌸🍃 Brown Sugar",
    desc: "",
    price: 120,
    img: "pink-lily-brown.jpeg",
    collection: ["graduation"],
    badge: "",
  },
];
